### ISSUE TITLE
Installing devml on Spark 2.3 fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by sedgewickmm18** [noahgift/devml#28]
Installing devml locally or on a standalone Jupyter notebook works fine, but installation on a Spark executor fails.

```Waiting for a Spark session to start...
Spark Initialization Done! ApplicationId = app-20190606023318-0000
KERNEL_ID = c65ad2be-4590-4e27-ae70-010473362fb7
Collecting devml
  Downloading https://files.pythonhosted.org/packages/fc/b7/7fc5c02b9741ba3ba5966347f1231fc0e6f384f3311a3a00f514ac282165/devml-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8cqaw681/devml/setup.py", line 11, in <module>
        LONG = open('README.rst').read()
      File "/opt/ibm/conda/miniconda36/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1190: ordinal not in range(128)Waiting for a Spark session to start...
Spark Initialization Done! ApplicationId = app-20190606023318-0000
KERNEL_ID = c65ad2be-4590-4e27-ae70-010473362fb7
Collecting devml
  Downloading https://files.pythonhosted.org/packages/fc/b7/7fc5c02b9741ba3ba5966347f1231fc0e6f384f3311a3a00f514ac282165/devml-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8cqaw681/devml/setup.py", line 11, in <module>
        LONG = open('README.rst').read()
      File "/opt/ibm/conda/miniconda36/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1190: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8cqaw681/devml/
```
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8cqaw681/devml/

**Comment by noahgift** [comment]
hmm, that is interesting!  pull requests are accepted.
